export const TASK_GET_TASKS_REQUEST = "TASK_GET_TASKS_REQUEST";
export const TASK_GET_TASKS_SUCCESS = "TASK_GET_TASKS_SUCCESS";
export const TASK_GET_TASKS_ERROR = "TASK_GET_TASKS_ERROR";

export const TASK_GET_PROJECTS_SUCCESS = "TASK_GET_PROJECTS_SUCCESS";

export const TASK_ADD_TASK_REQUEST = "TASK_ADD_TASK_REQUEST";
export const TASK_ADD_TASK_SUCCESS = "TASK_ADD_TASK_SUCCESS";
export const TASK_ADD_TASK_ERROR = "TASK_ADD_TASK_ERROR";

export const TASK_SET_FILTER_FIELD_PROJECT = "TASK_SET_FILTER_FIELD_PROJECT";
